#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingRoomBooking.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbMeetingRoomBooking_dev")]
	public partial class dbMeetingRoomBookingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDOC_BOOKING(DOC_BOOKING instance);
    partial void UpdateDOC_BOOKING(DOC_BOOKING instance);
    partial void DeleteDOC_BOOKING(DOC_BOOKING instance);
    partial void InsertDOC_BOOKING_D(DOC_BOOKING_D instance);
    partial void UpdateDOC_BOOKING_D(DOC_BOOKING_D instance);
    partial void DeleteDOC_BOOKING_D(DOC_BOOKING_D instance);
    partial void InsertDOC_BOOKING_I(DOC_BOOKING_I instance);
    partial void UpdateDOC_BOOKING_I(DOC_BOOKING_I instance);
    partial void DeleteDOC_BOOKING_I(DOC_BOOKING_I instance);
    partial void InsertDOC_BOOKING_T(DOC_BOOKING_T instance);
    partial void UpdateDOC_BOOKING_T(DOC_BOOKING_T instance);
    partial void DeleteDOC_BOOKING_T(DOC_BOOKING_T instance);
    partial void InsertLOG_BOOKING(LOG_BOOKING instance);
    partial void UpdateLOG_BOOKING(LOG_BOOKING instance);
    partial void DeleteLOG_BOOKING(LOG_BOOKING instance);
    partial void InsertMAS_DM(MAS_DM instance);
    partial void UpdateMAS_DM(MAS_DM instance);
    partial void DeleteMAS_DM(MAS_DM instance);
    partial void InsertMAS_DRINK(MAS_DRINK instance);
    partial void UpdateMAS_DRINK(MAS_DRINK instance);
    partial void DeleteMAS_DRINK(MAS_DRINK instance);
    partial void InsertMAS_RM_TM(MAS_RM_TM instance);
    partial void UpdateMAS_RM_TM(MAS_RM_TM instance);
    partial void DeleteMAS_RM_TM(MAS_RM_TM instance);
    partial void InsertMAS_RN(MAS_RN instance);
    partial void UpdateMAS_RN(MAS_RN instance);
    partial void DeleteMAS_RN(MAS_RN instance);
    partial void InsertMAS_ROOM(MAS_ROOM instance);
    partial void UpdateMAS_ROOM(MAS_ROOM instance);
    partial void DeleteMAS_ROOM(MAS_ROOM instance);
    partial void InsertMAS_ST(MAS_ST instance);
    partial void UpdateMAS_ST(MAS_ST instance);
    partial void DeleteMAS_ST(MAS_ST instance);
    partial void InsertMAS_TIME(MAS_TIME instance);
    partial void UpdateMAS_TIME(MAS_TIME instance);
    partial void DeleteMAS_TIME(MAS_TIME instance);
    partial void InsertMAS_TOOL(MAS_TOOL instance);
    partial void UpdateMAS_TOOL(MAS_TOOL instance);
    partial void DeleteMAS_TOOL(MAS_TOOL instance);
    #endregion
		
		public dbMeetingRoomBookingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbMeetingRoomBooking_devConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbMeetingRoomBookingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMeetingRoomBookingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMeetingRoomBookingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMeetingRoomBookingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DOC_BOOKING> DOC_BOOKINGs
		{
			get
			{
				return this.GetTable<DOC_BOOKING>();
			}
		}
		
		public System.Data.Linq.Table<DOC_BOOKING_D> DOC_BOOKING_Ds
		{
			get
			{
				return this.GetTable<DOC_BOOKING_D>();
			}
		}
		
		public System.Data.Linq.Table<DOC_BOOKING_I> DOC_BOOKING_Is
		{
			get
			{
				return this.GetTable<DOC_BOOKING_I>();
			}
		}
		
		public System.Data.Linq.Table<DOC_BOOKING_T> DOC_BOOKING_Ts
		{
			get
			{
				return this.GetTable<DOC_BOOKING_T>();
			}
		}
		
		public System.Data.Linq.Table<LOG_BOOKING> LOG_BOOKINGs
		{
			get
			{
				return this.GetTable<LOG_BOOKING>();
			}
		}
		
		public System.Data.Linq.Table<MAS_DM> MAS_DMs
		{
			get
			{
				return this.GetTable<MAS_DM>();
			}
		}
		
		public System.Data.Linq.Table<MAS_DRINK> MAS_DRINKs
		{
			get
			{
				return this.GetTable<MAS_DRINK>();
			}
		}
		
		public System.Data.Linq.Table<MAS_RM_TM> MAS_RM_TMs
		{
			get
			{
				return this.GetTable<MAS_RM_TM>();
			}
		}
		
		public System.Data.Linq.Table<MAS_RN> MAS_RNs
		{
			get
			{
				return this.GetTable<MAS_RN>();
			}
		}
		
		public System.Data.Linq.Table<MAS_ROOM> MAS_ROOMs
		{
			get
			{
				return this.GetTable<MAS_ROOM>();
			}
		}
		
		public System.Data.Linq.Table<MAS_ST> MAS_STs
		{
			get
			{
				return this.GetTable<MAS_ST>();
			}
		}
		
		public System.Data.Linq.Table<MAS_TIME> MAS_TIMEs
		{
			get
			{
				return this.GetTable<MAS_TIME>();
			}
		}
		
		public System.Data.Linq.Table<MAS_TOOL> MAS_TOOLs
		{
			get
			{
				return this.GetTable<MAS_TOOL>();
			}
		}
		
		public System.Data.Linq.Table<T_MAS_ROOM> T_MAS_ROOMs
		{
			get
			{
				return this.GetTable<T_MAS_ROOM>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MP_GET_ID")]
		public ISingleResult<MP_GET_IDResult> MP_GET_ID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STCODE", DbType="VarChar(20)")] string sTCODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCTYPE", DbType="VarChar(20)")] string dOCTYPE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTCODE, dOCTYPE);
			return ((ISingleResult<MP_GET_IDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MP_PREPARE_USER", IsComposable=true)]
		public object MP_PREPARE_USER()
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MP_SET_ID")]
		public int MP_SET_ID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STCODE", DbType="VarChar(20)")] string sTCODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCTYPE", DbType="VarChar(20)")] string dOCTYPE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTCODE, dOCTYPE);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOC_BOOKING")]
	public partial class DOC_BOOKING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _SCREATE;
		
		private System.Nullable<System.DateTime> _SUPDATE;
		
		private string _UCREATE;
		
		private string _UUPDATE;
		
		private string _DOCNO;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _STCODE;
		
		private string _DMCODE;
		
		private string _RMCODE;
		
		private System.Nullable<int> _QTY;
		
		private string _DESCRIPTION;
		
		private System.Nullable<int> _CFLAG;
		
		private EntitySet<DOC_BOOKING_D> _DOC_BOOKING_Ds;
		
		private EntitySet<DOC_BOOKING_I> _DOC_BOOKING_Is;
		
		private EntitySet<DOC_BOOKING_T> _DOC_BOOKING_Ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCREATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSCREATEChanged();
    partial void OnSUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSUPDATEChanged();
    partial void OnUCREATEChanging(string value);
    partial void OnUCREATEChanged();
    partial void OnUUPDATEChanging(string value);
    partial void OnUUPDATEChanged();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnDMCODEChanging(string value);
    partial void OnDMCODEChanged();
    partial void OnRMCODEChanging(string value);
    partial void OnRMCODEChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public DOC_BOOKING()
		{
			this._DOC_BOOKING_Ds = new EntitySet<DOC_BOOKING_D>(new Action<DOC_BOOKING_D>(this.attach_DOC_BOOKING_Ds), new Action<DOC_BOOKING_D>(this.detach_DOC_BOOKING_Ds));
			this._DOC_BOOKING_Is = new EntitySet<DOC_BOOKING_I>(new Action<DOC_BOOKING_I>(this.attach_DOC_BOOKING_Is), new Action<DOC_BOOKING_I>(this.detach_DOC_BOOKING_Is));
			this._DOC_BOOKING_Ts = new EntitySet<DOC_BOOKING_T>(new Action<DOC_BOOKING_T>(this.attach_DOC_BOOKING_Ts), new Action<DOC_BOOKING_T>(this.detach_DOC_BOOKING_Ts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCREATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCREATE
		{
			get
			{
				return this._SCREATE;
			}
			set
			{
				if ((this._SCREATE != value))
				{
					this.OnSCREATEChanging(value);
					this.SendPropertyChanging();
					this._SCREATE = value;
					this.SendPropertyChanged("SCREATE");
					this.OnSCREATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SUPDATE
		{
			get
			{
				return this._SUPDATE;
			}
			set
			{
				if ((this._SUPDATE != value))
				{
					this.OnSUPDATEChanging(value);
					this.SendPropertyChanging();
					this._SUPDATE = value;
					this.SendPropertyChanged("SUPDATE");
					this.OnSUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UCREATE", DbType="VarChar(20)")]
		public string UCREATE
		{
			get
			{
				return this._UCREATE;
			}
			set
			{
				if ((this._UCREATE != value))
				{
					this.OnUCREATEChanging(value);
					this.SendPropertyChanging();
					this._UCREATE = value;
					this.SendPropertyChanged("UCREATE");
					this.OnUCREATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UUPDATE", DbType="VarChar(20)")]
		public string UUPDATE
		{
			get
			{
				return this._UUPDATE;
			}
			set
			{
				if ((this._UUPDATE != value))
				{
					this.OnUUPDATEChanging(value);
					this.SendPropertyChanging();
					this._UUPDATE = value;
					this.SendPropertyChanged("UUPDATE");
					this.OnUUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(20)")]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMCODE", DbType="VarChar(20)")]
		public string DMCODE
		{
			get
			{
				return this._DMCODE;
			}
			set
			{
				if ((this._DMCODE != value))
				{
					this.OnDMCODEChanging(value);
					this.SendPropertyChanging();
					this._DMCODE = value;
					this.SendPropertyChanged("DMCODE");
					this.OnDMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMCODE", DbType="VarChar(20)")]
		public string RMCODE
		{
			get
			{
				return this._RMCODE;
			}
			set
			{
				if ((this._RMCODE != value))
				{
					this.OnRMCODEChanging(value);
					this.SendPropertyChanging();
					this._RMCODE = value;
					this.SendPropertyChanged("RMCODE");
					this.OnRMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(1000)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOC_BOOKING_DOC_BOOKING_D", Storage="_DOC_BOOKING_Ds", ThisKey="DOCNO", OtherKey="DOCNO")]
		public EntitySet<DOC_BOOKING_D> DOC_BOOKING_Ds
		{
			get
			{
				return this._DOC_BOOKING_Ds;
			}
			set
			{
				this._DOC_BOOKING_Ds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOC_BOOKING_DOC_BOOKING_I", Storage="_DOC_BOOKING_Is", ThisKey="DOCNO", OtherKey="DOCNO")]
		public EntitySet<DOC_BOOKING_I> DOC_BOOKING_Is
		{
			get
			{
				return this._DOC_BOOKING_Is;
			}
			set
			{
				this._DOC_BOOKING_Is.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOC_BOOKING_DOC_BOOKING_T", Storage="_DOC_BOOKING_Ts", ThisKey="DOCNO", OtherKey="DOCNO")]
		public EntitySet<DOC_BOOKING_T> DOC_BOOKING_Ts
		{
			get
			{
				return this._DOC_BOOKING_Ts;
			}
			set
			{
				this._DOC_BOOKING_Ts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DOC_BOOKING_Ds(DOC_BOOKING_D entity)
		{
			this.SendPropertyChanging();
			entity.DOC_BOOKING = this;
		}
		
		private void detach_DOC_BOOKING_Ds(DOC_BOOKING_D entity)
		{
			this.SendPropertyChanging();
			entity.DOC_BOOKING = null;
		}
		
		private void attach_DOC_BOOKING_Is(DOC_BOOKING_I entity)
		{
			this.SendPropertyChanging();
			entity.DOC_BOOKING = this;
		}
		
		private void detach_DOC_BOOKING_Is(DOC_BOOKING_I entity)
		{
			this.SendPropertyChanging();
			entity.DOC_BOOKING = null;
		}
		
		private void attach_DOC_BOOKING_Ts(DOC_BOOKING_T entity)
		{
			this.SendPropertyChanging();
			entity.DOC_BOOKING = this;
		}
		
		private void detach_DOC_BOOKING_Ts(DOC_BOOKING_T entity)
		{
			this.SendPropertyChanging();
			entity.DOC_BOOKING = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOC_BOOKING_D")]
	public partial class DOC_BOOKING_D : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private System.Nullable<int> _ITEMNO;
		
		private string _TDCODE;
		
		private EntityRef<DOC_BOOKING> _DOC_BOOKING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnITEMNOChanging(System.Nullable<int> value);
    partial void OnITEMNOChanged();
    partial void OnTDCODEChanging(string value);
    partial void OnTDCODEChanged();
    #endregion
		
		public DOC_BOOKING_D()
		{
			this._DOC_BOOKING = default(EntityRef<DOC_BOOKING>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					if (this._DOC_BOOKING.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMNO", DbType="Int")]
		public System.Nullable<int> ITEMNO
		{
			get
			{
				return this._ITEMNO;
			}
			set
			{
				if ((this._ITEMNO != value))
				{
					this.OnITEMNOChanging(value);
					this.SendPropertyChanging();
					this._ITEMNO = value;
					this.SendPropertyChanged("ITEMNO");
					this.OnITEMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TDCODE
		{
			get
			{
				return this._TDCODE;
			}
			set
			{
				if ((this._TDCODE != value))
				{
					this.OnTDCODEChanging(value);
					this.SendPropertyChanging();
					this._TDCODE = value;
					this.SendPropertyChanged("TDCODE");
					this.OnTDCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOC_BOOKING_DOC_BOOKING_D", Storage="_DOC_BOOKING", ThisKey="DOCNO", OtherKey="DOCNO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DOC_BOOKING DOC_BOOKING
		{
			get
			{
				return this._DOC_BOOKING.Entity;
			}
			set
			{
				DOC_BOOKING previousValue = this._DOC_BOOKING.Entity;
				if (((previousValue != value) 
							|| (this._DOC_BOOKING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOC_BOOKING.Entity = null;
						previousValue.DOC_BOOKING_Ds.Remove(this);
					}
					this._DOC_BOOKING.Entity = value;
					if ((value != null))
					{
						value.DOC_BOOKING_Ds.Add(this);
						this._DOCNO = value.DOCNO;
					}
					else
					{
						this._DOCNO = default(string);
					}
					this.SendPropertyChanged("DOC_BOOKING");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOC_BOOKING_I")]
	public partial class DOC_BOOKING_I : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private System.Nullable<int> _ITEMNO;
		
		private string _TMCODE;
		
		private EntityRef<DOC_BOOKING> _DOC_BOOKING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnITEMNOChanging(System.Nullable<int> value);
    partial void OnITEMNOChanged();
    partial void OnTMCODEChanging(string value);
    partial void OnTMCODEChanged();
    #endregion
		
		public DOC_BOOKING_I()
		{
			this._DOC_BOOKING = default(EntityRef<DOC_BOOKING>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					if (this._DOC_BOOKING.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMNO", DbType="Int")]
		public System.Nullable<int> ITEMNO
		{
			get
			{
				return this._ITEMNO;
			}
			set
			{
				if ((this._ITEMNO != value))
				{
					this.OnITEMNOChanging(value);
					this.SendPropertyChanging();
					this._ITEMNO = value;
					this.SendPropertyChanged("ITEMNO");
					this.OnITEMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					this.OnTMCODEChanging(value);
					this.SendPropertyChanging();
					this._TMCODE = value;
					this.SendPropertyChanged("TMCODE");
					this.OnTMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOC_BOOKING_DOC_BOOKING_I", Storage="_DOC_BOOKING", ThisKey="DOCNO", OtherKey="DOCNO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DOC_BOOKING DOC_BOOKING
		{
			get
			{
				return this._DOC_BOOKING.Entity;
			}
			set
			{
				DOC_BOOKING previousValue = this._DOC_BOOKING.Entity;
				if (((previousValue != value) 
							|| (this._DOC_BOOKING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOC_BOOKING.Entity = null;
						previousValue.DOC_BOOKING_Is.Remove(this);
					}
					this._DOC_BOOKING.Entity = value;
					if ((value != null))
					{
						value.DOC_BOOKING_Is.Add(this);
						this._DOCNO = value.DOCNO;
					}
					else
					{
						this._DOCNO = default(string);
					}
					this.SendPropertyChanged("DOC_BOOKING");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOC_BOOKING_T")]
	public partial class DOC_BOOKING_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private System.Nullable<int> _ITEMNO;
		
		private string _TLCODE;
		
		private EntityRef<DOC_BOOKING> _DOC_BOOKING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnITEMNOChanging(System.Nullable<int> value);
    partial void OnITEMNOChanged();
    partial void OnTLCODEChanging(string value);
    partial void OnTLCODEChanged();
    #endregion
		
		public DOC_BOOKING_T()
		{
			this._DOC_BOOKING = default(EntityRef<DOC_BOOKING>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					if (this._DOC_BOOKING.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMNO", DbType="Int")]
		public System.Nullable<int> ITEMNO
		{
			get
			{
				return this._ITEMNO;
			}
			set
			{
				if ((this._ITEMNO != value))
				{
					this.OnITEMNOChanging(value);
					this.SendPropertyChanging();
					this._ITEMNO = value;
					this.SendPropertyChanged("ITEMNO");
					this.OnITEMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TLCODE
		{
			get
			{
				return this._TLCODE;
			}
			set
			{
				if ((this._TLCODE != value))
				{
					this.OnTLCODEChanging(value);
					this.SendPropertyChanging();
					this._TLCODE = value;
					this.SendPropertyChanged("TLCODE");
					this.OnTLCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOC_BOOKING_DOC_BOOKING_T", Storage="_DOC_BOOKING", ThisKey="DOCNO", OtherKey="DOCNO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DOC_BOOKING DOC_BOOKING
		{
			get
			{
				return this._DOC_BOOKING.Entity;
			}
			set
			{
				DOC_BOOKING previousValue = this._DOC_BOOKING.Entity;
				if (((previousValue != value) 
							|| (this._DOC_BOOKING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOC_BOOKING.Entity = null;
						previousValue.DOC_BOOKING_Ts.Remove(this);
					}
					this._DOC_BOOKING.Entity = value;
					if ((value != null))
					{
						value.DOC_BOOKING_Ts.Add(this);
						this._DOCNO = value.DOCNO;
					}
					else
					{
						this._DOCNO = default(string);
					}
					this.SendPropertyChanged("DOC_BOOKING");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOG_BOOKING")]
	public partial class LOG_BOOKING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private System.DateTime _DOCDATE;
		
		private string _STCODE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnDOCDATEChanging(System.DateTime value);
    partial void OnDOCDATEChanged();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    #endregion
		
		public LOG_BOOKING()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_DM")]
	public partial class MAS_DM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DMCODE;
		
		private string _DMNAME;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDMCODEChanging(string value);
    partial void OnDMCODEChanged();
    partial void OnDMNAMEChanging(string value);
    partial void OnDMNAMEChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_DM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DMCODE
		{
			get
			{
				return this._DMCODE;
			}
			set
			{
				if ((this._DMCODE != value))
				{
					this.OnDMCODEChanging(value);
					this.SendPropertyChanging();
					this._DMCODE = value;
					this.SendPropertyChanged("DMCODE");
					this.OnDMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMNAME", DbType="VarChar(200)")]
		public string DMNAME
		{
			get
			{
				return this._DMNAME;
			}
			set
			{
				if ((this._DMNAME != value))
				{
					this.OnDMNAMEChanging(value);
					this.SendPropertyChanging();
					this._DMNAME = value;
					this.SendPropertyChanged("DMNAME");
					this.OnDMNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_DRINK")]
	public partial class MAS_DRINK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TDCODE;
		
		private string _NAME;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTDCODEChanging(string value);
    partial void OnTDCODEChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_DRINK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TDCODE
		{
			get
			{
				return this._TDCODE;
			}
			set
			{
				if ((this._TDCODE != value))
				{
					this.OnTDCODEChanging(value);
					this.SendPropertyChanging();
					this._TDCODE = value;
					this.SendPropertyChanged("TDCODE");
					this.OnTDCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(200)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_RM_TM")]
	public partial class MAS_RM_TM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RMCODE;
		
		private System.DateTime _DOCDATE;
		
		private string _TMCODE;
		
		private string _DOCNO;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRMCODEChanging(string value);
    partial void OnRMCODEChanged();
    partial void OnDOCDATEChanging(System.DateTime value);
    partial void OnDOCDATEChanged();
    partial void OnTMCODEChanging(string value);
    partial void OnTMCODEChanged();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_RM_TM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RMCODE
		{
			get
			{
				return this._RMCODE;
			}
			set
			{
				if ((this._RMCODE != value))
				{
					this.OnRMCODEChanging(value);
					this.SendPropertyChanging();
					this._RMCODE = value;
					this.SendPropertyChanged("RMCODE");
					this.OnRMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					this.OnTMCODEChanging(value);
					this.SendPropertyChanging();
					this._TMCODE = value;
					this.SendPropertyChanged("TMCODE");
					this.OnTMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(20)")]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_RN")]
	public partial class MAS_RN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STCODE;
		
		private string _DOCTYPE;
		
		private System.Nullable<int> _YEAR;
		
		private System.Nullable<int> _MONTH;
		
		private System.Nullable<int> _DAY;
		
		private System.Nullable<int> _NUMBER;
		
		private System.Nullable<int> _L_YEAR;
		
		private System.Nullable<int> _L_MONTH;
		
		private System.Nullable<int> _L_DAY;
		
		private System.Nullable<int> _L_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnDOCTYPEChanging(string value);
    partial void OnDOCTYPEChanged();
    partial void OnYEARChanging(System.Nullable<int> value);
    partial void OnYEARChanged();
    partial void OnMONTHChanging(System.Nullable<int> value);
    partial void OnMONTHChanged();
    partial void OnDAYChanging(System.Nullable<int> value);
    partial void OnDAYChanged();
    partial void OnNUMBERChanging(System.Nullable<int> value);
    partial void OnNUMBERChanged();
    partial void OnL_YEARChanging(System.Nullable<int> value);
    partial void OnL_YEARChanged();
    partial void OnL_MONTHChanging(System.Nullable<int> value);
    partial void OnL_MONTHChanged();
    partial void OnL_DAYChanging(System.Nullable<int> value);
    partial void OnL_DAYChanged();
    partial void OnL_NUMBERChanging(System.Nullable<int> value);
    partial void OnL_NUMBERChanged();
    #endregion
		
		public MAS_RN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this.OnDOCTYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCTYPE = value;
					this.SendPropertyChanged("DOCTYPE");
					this.OnDOCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTH", DbType="Int")]
		public System.Nullable<int> MONTH
		{
			get
			{
				return this._MONTH;
			}
			set
			{
				if ((this._MONTH != value))
				{
					this.OnMONTHChanging(value);
					this.SendPropertyChanging();
					this._MONTH = value;
					this.SendPropertyChanged("MONTH");
					this.OnMONTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAY", DbType="Int")]
		public System.Nullable<int> DAY
		{
			get
			{
				return this._DAY;
			}
			set
			{
				if ((this._DAY != value))
				{
					this.OnDAYChanging(value);
					this.SendPropertyChanging();
					this._DAY = value;
					this.SendPropertyChanged("DAY");
					this.OnDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER", DbType="Int")]
		public System.Nullable<int> NUMBER
		{
			get
			{
				return this._NUMBER;
			}
			set
			{
				if ((this._NUMBER != value))
				{
					this.OnNUMBERChanging(value);
					this.SendPropertyChanging();
					this._NUMBER = value;
					this.SendPropertyChanged("NUMBER");
					this.OnNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_YEAR", DbType="Int")]
		public System.Nullable<int> L_YEAR
		{
			get
			{
				return this._L_YEAR;
			}
			set
			{
				if ((this._L_YEAR != value))
				{
					this.OnL_YEARChanging(value);
					this.SendPropertyChanging();
					this._L_YEAR = value;
					this.SendPropertyChanged("L_YEAR");
					this.OnL_YEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_MONTH", DbType="Int")]
		public System.Nullable<int> L_MONTH
		{
			get
			{
				return this._L_MONTH;
			}
			set
			{
				if ((this._L_MONTH != value))
				{
					this.OnL_MONTHChanging(value);
					this.SendPropertyChanging();
					this._L_MONTH = value;
					this.SendPropertyChanged("L_MONTH");
					this.OnL_MONTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_DAY", DbType="Int")]
		public System.Nullable<int> L_DAY
		{
			get
			{
				return this._L_DAY;
			}
			set
			{
				if ((this._L_DAY != value))
				{
					this.OnL_DAYChanging(value);
					this.SendPropertyChanging();
					this._L_DAY = value;
					this.SendPropertyChanged("L_DAY");
					this.OnL_DAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_NUMBER", DbType="Int")]
		public System.Nullable<int> L_NUMBER
		{
			get
			{
				return this._L_NUMBER;
			}
			set
			{
				if ((this._L_NUMBER != value))
				{
					this.OnL_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._L_NUMBER = value;
					this.SendPropertyChanged("L_NUMBER");
					this.OnL_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_ROOM")]
	public partial class MAS_ROOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RMCODE;
		
		private string _RMNAME;
		
		private System.Nullable<int> _MIN_QTY;
		
		private System.Nullable<int> _MAX_QTY;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRMCODEChanging(string value);
    partial void OnRMCODEChanged();
    partial void OnRMNAMEChanging(string value);
    partial void OnRMNAMEChanged();
    partial void OnMIN_QTYChanging(System.Nullable<int> value);
    partial void OnMIN_QTYChanged();
    partial void OnMAX_QTYChanging(System.Nullable<int> value);
    partial void OnMAX_QTYChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_ROOM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RMCODE
		{
			get
			{
				return this._RMCODE;
			}
			set
			{
				if ((this._RMCODE != value))
				{
					this.OnRMCODEChanging(value);
					this.SendPropertyChanging();
					this._RMCODE = value;
					this.SendPropertyChanged("RMCODE");
					this.OnRMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMNAME", DbType="VarChar(200)")]
		public string RMNAME
		{
			get
			{
				return this._RMNAME;
			}
			set
			{
				if ((this._RMNAME != value))
				{
					this.OnRMNAMEChanging(value);
					this.SendPropertyChanging();
					this._RMNAME = value;
					this.SendPropertyChanged("RMNAME");
					this.OnRMNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIN_QTY", DbType="Int")]
		public System.Nullable<int> MIN_QTY
		{
			get
			{
				return this._MIN_QTY;
			}
			set
			{
				if ((this._MIN_QTY != value))
				{
					this.OnMIN_QTYChanging(value);
					this.SendPropertyChanging();
					this._MIN_QTY = value;
					this.SendPropertyChanged("MIN_QTY");
					this.OnMIN_QTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_QTY", DbType="Int")]
		public System.Nullable<int> MAX_QTY
		{
			get
			{
				return this._MAX_QTY;
			}
			set
			{
				if ((this._MAX_QTY != value))
				{
					this.OnMAX_QTYChanging(value);
					this.SendPropertyChanging();
					this._MAX_QTY = value;
					this.SendPropertyChanged("MAX_QTY");
					this.OnMAX_QTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_ST")]
	public partial class MAS_ST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STCODE;
		
		private string _STNAME;
		
		private string _STPASSWORD;
		
		private string _EMAIL;
		
		private System.Nullable<int> _PERMISSION;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnSTNAMEChanging(string value);
    partial void OnSTNAMEChanged();
    partial void OnSTPASSWORDChanging(string value);
    partial void OnSTPASSWORDChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPERMISSIONChanging(System.Nullable<int> value);
    partial void OnPERMISSIONChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_ST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STNAME", DbType="VarChar(200)")]
		public string STNAME
		{
			get
			{
				return this._STNAME;
			}
			set
			{
				if ((this._STNAME != value))
				{
					this.OnSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._STNAME = value;
					this.SendPropertyChanged("STNAME");
					this.OnSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STPASSWORD", DbType="VarChar(20)")]
		public string STPASSWORD
		{
			get
			{
				return this._STPASSWORD;
			}
			set
			{
				if ((this._STPASSWORD != value))
				{
					this.OnSTPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._STPASSWORD = value;
					this.SendPropertyChanged("STPASSWORD");
					this.OnSTPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERMISSION", DbType="Int")]
		public System.Nullable<int> PERMISSION
		{
			get
			{
				return this._PERMISSION;
			}
			set
			{
				if ((this._PERMISSION != value))
				{
					this.OnPERMISSIONChanging(value);
					this.SendPropertyChanging();
					this._PERMISSION = value;
					this.SendPropertyChanged("PERMISSION");
					this.OnPERMISSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_TIME")]
	public partial class MAS_TIME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TMCODE;
		
		private string _S_TIME;
		
		private string _E_TIME;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTMCODEChanging(string value);
    partial void OnTMCODEChanged();
    partial void OnS_TIMEChanging(string value);
    partial void OnS_TIMEChanged();
    partial void OnE_TIMEChanging(string value);
    partial void OnE_TIMEChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_TIME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					this.OnTMCODEChanging(value);
					this.SendPropertyChanging();
					this._TMCODE = value;
					this.SendPropertyChanged("TMCODE");
					this.OnTMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_TIME", DbType="VarChar(20)")]
		public string S_TIME
		{
			get
			{
				return this._S_TIME;
			}
			set
			{
				if ((this._S_TIME != value))
				{
					this.OnS_TIMEChanging(value);
					this.SendPropertyChanging();
					this._S_TIME = value;
					this.SendPropertyChanged("S_TIME");
					this.OnS_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TIME", DbType="VarChar(20)")]
		public string E_TIME
		{
			get
			{
				return this._E_TIME;
			}
			set
			{
				if ((this._E_TIME != value))
				{
					this.OnE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._E_TIME = value;
					this.SendPropertyChanged("E_TIME");
					this.OnE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_TOOLS")]
	public partial class MAS_TOOL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TLCODE;
		
		private string _NAME;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTLCODEChanging(string value);
    partial void OnTLCODEChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_TOOL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TLCODE
		{
			get
			{
				return this._TLCODE;
			}
			set
			{
				if ((this._TLCODE != value))
				{
					this.OnTLCODEChanging(value);
					this.SendPropertyChanging();
					this._TLCODE = value;
					this.SendPropertyChanged("TLCODE");
					this.OnTLCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(200)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_MAS_ROOM")]
	public partial class T_MAS_ROOM
	{
		
		private string _RMCODE;
		
		private string _RMNAME;
		
		private System.Nullable<int> _CFLAG;
		
		public T_MAS_ROOM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RMCODE
		{
			get
			{
				return this._RMCODE;
			}
			set
			{
				if ((this._RMCODE != value))
				{
					this._RMCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMNAME", DbType="VarChar(200)")]
		public string RMNAME
		{
			get
			{
				return this._RMNAME;
			}
			set
			{
				if ((this._RMNAME != value))
				{
					this._RMNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this._CFLAG = value;
				}
			}
		}
	}
	
	public partial class MP_GET_IDResult
	{
		
		private string _Column1;
		
		public MP_GET_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="NVarChar(4000)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
